services:
  jupyter:
    build:
      context: .
    ports:
      - 8888
    volumes:
      - jupyter-data:/home/work
    command: jupyter lab --port=8888 --allow-root

volumes:
  jupyter-data:
    name: jupyter-data
