from os import getenv

START_DATE = getenv("SATELLITE_EMBEDDING_START_DATE")
END_DATE = getenv("SATELLITE_EMBEDDING_END_DATE")
ROI = f"input/{getenv('SATELLITE_EMBEDDING_INPUT_ROI')}"
AGGREGATE = getenv("SATELLITE_EMBEDDING_AGGREGATE", "median")
RESOLUTION = int(getenv("SATELLITE_EMBEDDING_RESOLUTION", "10"))
OUTPUT_PREFIX = getenv("SATELLITE_EMBEDDING_OUTPUT_PREFIX")
